[book]
authors = ["glottologist"]
language = "en"
multilingual = false
src = "src"
title = "Circom Bootcamp Notes"

[build]

[preprocessor.gettext]
after = ["links"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.katex]
after = ["links"]


[output.html]
mathjax-support = true
git-repository-url = "https://github.com/glottologist/rare-skills-circom-bootcamp"
curly-quotes = true
additional-js = ["theme/speaker-notes.js","lib/mermaid.min.js", "lib/mermaid-init.js"]
additional-css = [
  "theme/css/svgbob.css",
  "theme/css/speaker-notes.css",
  "theme/css/language-picker.css",
  "theme/css/rtl.css",
]


[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
